version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/MC Controls"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
      - "area: backend"

  - package-ecosystem: "npm"
    directory: "/WebContent"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
      - "area: frontend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "area: github"
